project:
  type: website
  resources:
    - "pdf/"

website: 
  title: "Pingfan's Talks"
  description: "The slide and poster collection of Pingfan Hu"
  favicon: logo.png
  site-url: https://talks.pingfanhu.com
  repo-url: https://github.com/pingfan-hu/pingfanTalks
  back-to-top-navigation: false
  open-graph:
    locale: es_ES
    site-name: https://talks.pingfanhu.com
  page-footer:
    center: "© 2025 [Pingfan Hu](https://pingfanhu.com)"
    border: true
    background: light

format:
  html:
    toc: false
    theme: [united, themes/theme.scss]
    css: themes/styles.css
    self-contained: true
    link-external-newwindow: true
    link-external-icon: false
    backgroundcolor: "#F8F7F0"

knitr: 
  opts_chunk: 
    comment: "#>"
    fig.align: "center"
    fig.show: "hold"
    fig.asp: 0.618
    fig.retna: 3
    out.width: 80%
    echo: false

execute: 
  warning: false
